### ISSUE TITLE
Implement `Hash` for `Handle`

### ISSUE THREAD

**Issue by KodrAus** [BurntSushi/same-file#10]
[Relevant API Guideline](https://github.com/brson/rust-api-guidelines#types-eagerly-implement-common-traits-c-common-traits)

Implement the [`Hash`](https://doc.rust-lang.org/core/hash/trait.Hash.html) trait for `Handle`. See those docs for more details about how to implement `Hash`.

**Comment by BurntSushi** [comment]
What is the semantic meaning of an ordering between two handles? I'm not sure such a comparison makes sense?

Hashing seems reasonable to add.

**Comment by KodrAus** [comment]
I wasn't quite sure about `Ord` either, but it was mentioned in the evaluation as a good idea. I can't think of a use-case so maybe we just remove that one?
