### ISSUE TITLE
Start tracking release notes for version bumps

### ISSUE THREAD

**Issue by KodrAus** [BurntSushi/same-file#13]
[Relevant API Guideline](https://github.com/brson/rust-api-guidelines#release-notes-document-all-significant-changes-c-relnotes)

The API Guidelines recommend tracking changes between crate versions in release notes. I imagine you'll have some idea of how you want to do this already @BurntSushi.

**Comment by BurntSushi** [comment]
I'm going to hold off on this. I maintain a lot of crates, and tracking a full changelog for each of them is just too much work. For crates like this that don't get much activity, I don't think it's worth it. The commit log is small enough for someone to digest if they're really curious.
