### ISSUE TITLE
Clarify Approach to comparing files in docs

### ISSUE THREAD

**Issue by KodrAus** [BurntSushi/same-file#2]
Clarify the statement about false positives a little more in the crate docs for the [`same_file`](https://docs.rs/same-file/0.1.3/same_file/fn.is_same_file.html) method. This should be enough to encourage users to check the implementation if they have specific requirements, but not complicate things for users who aren't concerned.

**Comment by KodrAus** [comment]
I don't think I've put enough detail in this issue for someone to reasonably pick it up, and the work of describing what to do might be more than it takes to just do it. So I'll just open up a PR for it later today and we can bikeshed on that :)

**Comment by gurgalex** [comment]
Is the issue of false positives limited to when files are compared on Windows and are the same size?
If that's the case, would "comparing files of equal size can lead to false positives" suffice?

**Comment by BurntSushi** [comment]
@gurgalex That was my initial belief. From conversations on the [libz blitz forum thread](https://internals.rust-lang.org/t/out-of-band-crate-evaluation-for-2017-07-18-same-file/5457) though, it sounds like false positives can happen on Unix systems too, depending on the file system in use.

**Comment by KodrAus** [comment]
@gurgalex I didn't want to force someone to go dig through all the previous conversation on the lib blitz thread, but if you don't mind that and would like to work on this then feel free :+1:
