### ISSUE TITLE
Release 1.0 on crates.io

### ISSUE THREAD

**Issue by KodrAus** [BurntSushi/same-file#27]
The libz blitz evaluation is finished :tada: (a big thanks to everyone who contributed!). I guess the next steps are:

- [x] Final pass over documentation
- [ ] ~~Changelog (#13)~~
- [x] Release `1.0`

Does that sound right to you @BurntSushi?

**Comment by BurntSushi** [comment]
@KodrAus I think so! I'll get around to it as soon as I can. :-) Thanks again for all your work! You've been a huge help!

**Comment by BurntSushi** [comment]
Done! Thanks @KodrAus!

**Comment by KodrAus** [comment]
Woohoo! :tada:
