### ISSUE TITLE
Do a pass over documentation

### ISSUE THREAD

**Issue by KodrAus** [BurntSushi/same-file#28]
Before the stable release, we should do a full pass over the crate documentation and make sure:

- There aren't any grammatical errors in the prose
- It all flows nicely
- The examples are easy to follow and all make sense
- The links to other items all work

**Comment by gurgalex** [comment]
broken trait links found under struct `same_file::Handle`
`impl AsRawHandle for Handle`
`impl IntoRawHandle for Handle`
All the links contain
`/sys/imp/ext/`

Valid links replace it with
`/os/windows/`
valid links are
[AsRawHandle](https://doc.rust-lang.org/nightly/std/os/windows/io/trait.AsRawHandle.html)
[IntoRawHandle](https://doc.rust-lang.org/nightly/std/os/windows/io/trait.IntoRawHandle.html)

**Comment by KodrAus** [comment]
Thanks @gurgalex! Would you like to open a PR that fixes those up?

**Comment by gurgalex** [comment]
I'm not sure where or how the links are being generated sadly.
The src link points to [here](https://github.com/BurntSushi/same-file/blob/538a80b904105783b74305cb786746e7a4b2e5eb/src/win.rs#L97-L103), but there are no links there. So I assume something is linking to the std library docs automatically.

**Comment by gurgalex** [comment]
How is [cross platform](https://github.com/BurntSushi/same-file/blob/be98505cde8949963ada85eb8fb08a25a0db773c/src/lib.rs#L2) defined?
Does that mean it supports all [tier 1 platforms?](https://forge.rust-lang.org/platform-support.html)

**Comment by KodrAus** [comment]
Oh I see, those are rustdoc links, not links we've added to the prose. It looks like the `unix`-specific links are all ok. Maybe there's just a mismatch between the `nightly` that generated the docs on `docs.rs` and where it ends up linking? I'm not really sure though, I'll do some digging but hopefully a new release will just magically fix that.

> How is cross platform defined?

Excellent question! My reading is that it means all tier 1 platforms are fully supported with a consistent API.

**Comment by BurntSushi** [comment]
I did a brief pass over the docs and everything looks good to me. I don't think I checked every link, but we can clean those up whenever.
