### ISSUE TITLE
Add examples to public methods on `Handle`

### ISSUE THREAD

**Issue by KodrAus** [BurntSushi/same-file#3]
[Relevant API Guideline](https://github.com/brson/rust-api-guidelines#all-items-have-a-rustdoc-example-c-example)

Add an example to the following methods on [`Handle`](https://docs.rs/same-file/0.1.3/same_file/struct.Handle.html):

- `from_path`
- `from_file`
- `stdin`
- `stdout`
- `stderr`
- `as_file`
- `as_mut_file`

**Comment by yandexx** [comment]
Just leaving a note here that I'm working on the examples here and errors in #4.
