### ISSUE TITLE
Include license files

### ISSUE THREAD

**Issue by Nemo157** [BurntSushi/same-file#38]
The MIT license at least requires publishing with the source code to really be in effect. Although I believe you don't need to include a copy of the Unlicense, it would be nice to include it as well.

Also, there's a COPYING file that contains the BSD-3-Clause, is that intended to be part of this repository, or just leftover from the initial setup (I notice that it was introduced in the first commit and the readme included it, but the first commit also had `Unlicense/MIT` in the `Cargo.toml` and the readme was changed very soon after).

**Comment by BurntSushi** [comment]
Thanks for pointing this out. I've fixed it. I must have started this project by copying files from my `rust-snappy` repo, which is licensed under the BSD 3 clause (because it was very heavily influenced by extant implementations, of which were licensed under the same license).
