### ISSUE TITLE
Support stdin, stdout, and stderr in Windows Powershell

### ISSUE THREAD

**Issue by devnought** [BurntSushi/same-file#40]
Testing handle equality for file paths to streams works on Windows under `cmd`, however not from Powershell (tested with 5 and 6)

```
PS G:\dev\lib\same-file> cargo run --example is_stderr 2> examples/stderr
"examples/is_same_file.rs" is NOT stderr!
"examples/is_stderr.rs" is NOT stderr!
"examples/stderr" is NOT stderr!
```

**Comment by BurntSushi** [comment]
Interesting. Looks like a bug to me, but I haven't the fainest clue as to what's going on. I welcome others to try and investigate. :-)

**Comment by BurntSushi** [comment]
Closing since this appears stale.
