### ISSUE TITLE
False positive of two files are different

### ISSUE THREAD

**Issue by xxks-kkk** [BurntSushi/same-file#45]
I have two files both contains:

```
b94d27b9934d3e08a52e52d7da7dabfac484efe37a5380ee9088f7ace2efcde9
```

by invoking the assertion with `is_same_file`, error raises.

**Comment by BurntSushi** [comment]
The content of a file is irrelevant to what this crate does. The first line of documentation says:

> This crate provides a safe and simple cross platform way to determine whether two file paths refer to the same file or directory.
