### ISSUE TITLE
Unknown Targets

### ISSUE THREAD

**Issue by FreeMasen** [BurntSushi/same-file#46]
I am curious if you would be willing to add some default implementations to this crate to allow for compilation on unknown targets?

These implementations could panic on use but would allow this crate to compile. 

The reason I bring this up is that there seem to be a few libraries that are exposing this crate even though they aren't using the functionality. For example `mdbook` depends on handlebars (with default features) which depends on `walkdir` which depends on this crate. That means if I wanted to use the structs exported by the `mdbook` library in a project that is compiling to say `wasm32-unknown-unknown` the compiler stops me. This specific example could be solved by getting `mdbook`'s `handlebars` dependency updated to use the `no_dir_source` feature but since this isn't the first time I've run into this problem I thought it might be worth exploring solving it at this level. 

In most situations there would still be an issue at a higher level but it would at least alleviate a small amount of pain.

**Comment by BurntSushi** [comment]
Hmm, I think this might be a duplicate of #42?

It looks like the proposed solution in #42 is not to panic, but rather, to just return an error instead.

**Comment by FreeMasen** [comment]
Sorry about that I will close this one. I looked but apparently not too closely.

**Comment by BurntSushi** [comment]
No worries. The issue title wasn't great. I just updated it.
