### ISSUE TITLE
Add target 'wasm32-wasi' support ?

### ISSUE THREAD

**Issue by yanghaku** [BurntSushi/same-file#57]

**Comment by BurntSushi** [comment]
I don't know what this means or entails.

**Comment by yanghaku** [comment]
I'm compiling [coreutils](https://github.com/uutils/coreutils) to webassembly but many packages need this dependency ```same-file```, it cannot compile with target  ```wasm32-wasi```.

**Comment by BurntSushi** [comment]
Patches are welcome.

If the patch is invasive or requires new dependencies, it would be better to open an issue and write a more detailed proposal so that it can be discussed.

**Comment by yanghaku** [comment]
Thank you for your reply, I will search and think about more details about same-file for wasi, and then discuss about it.
