### ISSUE TITLE
Replace `try!` with `?` in examples

### ISSUE THREAD

**Issue by KodrAus** [BurntSushi/same-file#6]
[Relevant API Guideline](https://github.com/brson/rust-api-guidelines#examples-use--not-try-not-unwrap-c-question-mark)

Replace `try!` and `unwrap` with `?` in the two crate root examples.

See the API Guideline for an example of how to do this.

**Comment by BurntSushi** [comment]
Note that we'll need to bump the minimum Rust version from `1.10` to `1.16` for this. Which is OK.
