### ISSUE TITLE
Note why `Handle` methods in `unix` won't panic

### ISSUE THREAD

**Issue by KodrAus** [BurntSushi/same-file#7]
Relevant API Guidelines:
- [Panic Docs](https://github.com/brson/rust-api-guidelines#function-docs-include-panic-conditions-in-panics-section-c-panic-doc)
- [Destructors never fail](https://github.com/brson/rust-api-guidelines#destructors-never-fail-c-dtor-fail)

The [`unix`](https://github.com/BurntSushi/same-file/blob/master/src/unix.rs) implementation of `Handle` calls `unwrap` in the following methods:

- `Drop::drop`
- `AsRawFd::as_raw_fd`
- `IntoRawFd::into_raw_fd`
- `as_file`
- `as_file_mut`

These calls should either have a comment inline documenting why they can't fail, or a _Panics_ section should be added to the docs documenting when they will fail.

**Comment by yandexx** [comment]
Taking this as the idea is the same as with #8

**Comment by KodrAus** [comment]
I imagine the reasons for the `unwrap`s being safe in the `unix` mod are basically the same as the `win` mod.
